apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordsmith-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/heloise-viegas/wordsmith-kubernetes-files.git
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
