apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: api
  selector:
    app: api
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: heloise1/wordsmithapi:182
        ports:
        - containerPort: 8080
          name: api
